import React from "react";

const TermsAndConditions = () => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="p-6 max-w-5xl mx-auto">
      {/* Sticky Header */}
      <div className="sticky top-0 bg-white py-4 border-b flex justify-between items-center z-10">
        <h1 className="text-3xl font-bold">Terms & Conditions</h1>
        <button
          onClick={handlePrint}
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
        >
          Print / Download
        </button>
      </div>

      {/* Scrollable Content */}
      <div className="mt-6 border rounded-lg p-6 h-[70vh] overflow-y-auto leading-relaxed text-justify">
        <p>
          This document is an electronic record in terms of Information Technology
          Act, 2000 and rules there under as applicable and the amended provisions
          pertaining to electronic records in various statutes as amended by the
          Information Technology Act, 2000. This electronic record is generated by
          a computer system and does not require any physical or digital
          signatures.
        </p>

        <p className="mt-4">
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of domain name{" "}
          <strong>https://joyfulgenius.org/</strong> (“Website”), including the related
          mobile site and mobile application (hereinafter referred to as
          “Platform”).
        </p>

        <p className="mt-4">
          The Platform is owned by <strong>Joyful Genius</strong>, a company
          incorporated under the Companies Act, 1956 with its registered office
          at <strong>Old Agra Road, Vasind, Maharashtra</strong> (hereinafter referred
          to as "Platform Owner", "we", "us", "our").
        </p>

        <p className="mt-4">
          Your use of the Platform and services and tools are governed by the
          following terms and conditions ("Terms of Use") as applicable to the
          Platform including the applicable policies which are incorporated herein
          by way of reference. If You transact on the Platform, You shall be
          subject to the policies that are applicable to the Platform for such
          transaction. By mere use of the Platform, You shall be contracting with
          the Platform Owner and these terms and conditions including the policies
          constitute Your binding obligations, with Platform Owner.
        </p>

        <p className="mt-4">
          These Terms of Use relate to your use of our website, goods (as
          applicable) or services (as applicable) (collectively, “Services”). Any
          terms and conditions proposed by You which are in addition to or which
          conflict with these Terms of Use are expressly rejected by the Platform
          Owner and shall be of no force or effect. These Terms of Use can be
          modified at any time without assigning any reason. It is your
          responsibility to periodically review these Terms of Use to stay
          informed of updates.
        </p>

        <h2 className="mt-6 font-bold text-lg">By using our Platform, you agree to:</h2>
        <ul className="list-disc ml-6 mt-2 space-y-2">
          <li>Provide true, accurate and complete information during and after registration.</li>
          <li>Acknowledge that information and materials on the Platform may contain inaccuracies, for which we exclude liability to the fullest extent permitted by law.</li>
          <li>Use our Services entirely at your own risk and discretion, ensuring they meet your requirements.</li>
          <li>Not use the Platform for unlawful purposes or in violation of Indian laws.</li>
          <li>Pay the applicable charges for availing Services as communicated.</li>
          <li>Respect our intellectual property rights over Platform content, design, and graphics.</li>
        </ul>

        <h2 className="mt-6 font-bold text-lg">Liability & Indemnity</h2>
        <p className="mt-2">
          In no event will the Platform Owner be liable for any indirect,
          consequential, incidental, special or punitive damages, including loss
          of profits, data, or opportunities, whether in contract or otherwise.
          Our total liability shall not exceed the amount paid by you for the
          Services giving rise to the cause of action or ₹100, whichever is less.
        </p>

        <h2 className="mt-6 font-bold text-lg">Jurisdiction</h2>
        <p className="mt-2">
          These Terms shall be governed by the laws of India. All disputes shall
          be subject to the exclusive jurisdiction of the courts in{" "}
          <strong>Vasind, Maharashtra</strong>.
        </p>

        <h2 className="mt-6 font-bold text-lg">Contact Us</h2>
        <p className="mt-2">
          All concerns or communications relating to these Terms must be
          communicated to us using the contact information provided on this
          website.
        </p>
      </div>
    </div>
  );
};

export default TermsAndConditions;
